# Generated by Django 3.0.2 on 2020-05-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_schemas', '0003_remove_itemfield_create_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemschema',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemas', to='drf_schemas.Category'),
        ),
        migrations.AlterField(
            model_name='itemschema',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_images', to='drf_schemas.Image'),
        ),
    ]
