# Generated by Django 3.0.2 on 2020-05-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_schemas', '0005_auto_20200515_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleanfield',
            name='is_repr',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='choicesfield',
            name='is_repr',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='datetimefield',
            name='is_repr',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='numberfield',
            name='is_repr',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='textfield',
            name='is_repr',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='textfield',
            name='query',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
