# Generated by Django 3.0.2 on 2020-05-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_schemas', '0006_auto_20200515_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booleanfield',
            old_name='is_repr',
            new_name='represent',
        ),
        migrations.RenameField(
            model_name='choicesfield',
            old_name='is_repr',
            new_name='represent',
        ),
        migrations.RenameField(
            model_name='datetimefield',
            old_name='is_repr',
            new_name='represent',
        ),
        migrations.RenameField(
            model_name='numberfield',
            old_name='is_repr',
            new_name='represent',
        ),
        migrations.RenameField(
            model_name='textfield',
            old_name='is_repr',
            new_name='represent',
        ),
    ]
