# Generated by Django 3.0.2 on 2020-05-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_schemas', '0007_auto_20200515_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleanfield',
            name='represent',
        ),
        migrations.RemoveField(
            model_name='choicesfield',
            name='represent',
        ),
        migrations.RemoveField(
            model_name='datetimefield',
            name='represent',
        ),
        migrations.RemoveField(
            model_name='numberfield',
            name='represent',
        ),
    ]
